on: [push]
defaults:
  run:
    working-directory: ./
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.201'
      - run: dotnet test
        working-directory: Criipto.Signatures.UnitTests